tenant-id:
  attribute-key: ${TENANT_ID_ATTRIBUTE_KEY:tenant-id}
spring:
  data:
    mongodb:
      username: ${MONGODB_USERNAME:admin}
      password: ${MONGODB_PASSWORD:admin}
      host: ${MONGODB_HOST:localhost}
      port: ${MONGODB_PORT:27017}
      database: ${MONGODB_DATABASE:event-receiver}
      autoIndexCreation: true
    redis:
      host: ${REDIS_HOST:127.0.0.1}
      port: ${REDIS_PORT:6379}
      timeout: ${REDIS_TIMEOUT:6000}
      expiration: ${REDIS_EXPIRATION:600}
      tolerance: ${REDIS_CONNECTION_IS_TOLERANCE:true}
      max-downtime: ${REDIS_TOLERANCE_MAX_DOWNTIME:5m}
  cloud:
    stream:
      bindings:
        output:
          destination: ${TO_DEVICE_SERVICE_TOPIC:device-service}
    gcp:
      project-id: ${PROJECT_ID:single-system}
  kafka:
    producer:
      tenants-sending-data-topic: ${TENANTS_SENDING_DATA:tenants-sending-data}
      bootstrap-servers: ${KAFKA_PRODUCER_BOOTSTRAP_SERVER:localhost:9092}
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      bootstrap-servers: ${KAFKA_PRODUCER_BOOTSTRAP_SERVER:localhost:9092}
server:
  port: ${SERVER_PORT:9096}
management:
  health:
    redis:
      enabled: false
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: ${ACTUATOR_EXPOSE_ENDPOINTS:*}
  info:
    git:
      enabled: true
  server:
    port: ${ACTUATOR_PORT:8066}
rest:
  exception:
    handlers:
      include:
        internal-server-exception: true
mongock:
  change-logs-scan-package:
    - com.ynero.ss.event_receiver.migration