tenant-id:
  attribute-key: ${TENANT_ID_ATTRIBUTE_KEY:tenant-id}

spring:
  data:
    redis:
      host: ${REDIS_HOST:127.0.0.1}
      port: ${REDIS_PORT:6379}
      timeout: 6000
      expiration: 600
  cloud:
    stream:
      bindings:
        output:
          destination: ${TOPIC:device-service}
    gcp:
      project-id: ${PROJECT_ID:single-system}
  producer:
    tenants-sending-data-topic: ${TENANTS_SENDING_DATA:tenants-sending-data}
    bootstrap-servers: ${KAFKA_PRODUCER_BOOTSTRAP_SERVER:localhost:9092}
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.springframework.kafka.support.serializer.JsonSerializer