apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.deployment.name}}
  labels:
    app: event-receiver-app
    workload: {{.Values.deployment.name}}
spec:
  replicas: {{.Values.deployment.replicaCount}}
  selector:
    matchLabels:
      app: event-receiver-app
      workload: {{.Values.deployment.name}}
  template:
    metadata:
      labels:
        app: event-receiver-app
        workload: {{.Values.deployment.name}}
    spec:
      volumes:
        - name: google-cloud-key
          secret:
            secretName: event-receiver-sa-key
      containers:
        - name: {{.Values.deployment.name}}
          image: "gcr.io/single-system-dev/event-receiver:{{.Values.app.version}}"
          resources:
            requests:
              cpu: {{ .Values.deployment.containers.resources.requests.cpu }}
              memory: {{ .Values.deployment.containers.resources.requests.memory }}
            limits:
              cpu: {{ .Values.deployment.containers.resources.limits.cpu }}
              memory: {{ .Values.deployment.containers.resources.limits.memory }}
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: {{.Values.actuator.server.port}}
          ports:
            - containerPort: {{.Values.deployment.port}}
            - containerPort: {{.Values.actuator.server.port}}
          volumeMounts:
            - name: google-cloud-key
              mountPath: /var/secrets/google
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/google/key.json
            - name: TENANT_ID_ATTRIBUTE_KEY
              value: "{{ .Values.deployment.tenant.id.attribute.key}}"
            - name: MONGODB_USERNAME
              value: "{{ .Values.deployment.mongo.username}}"
            - name: MONGODB_PASSWORD
              value: "{{ .Values.deployment.mongo.password}}"
            - name: MONGODB_HOST
              value: "{{ .Values.deployment.mongo.host}}"
            - name: MONGODB_PORT
              value: "{{ .Values.deployment.mongo.port}}"
            - name: MONGODB_DATABASE
              value: "{{ .Values.deployment.mongo.database}}"
            - name: REDIS_HOST
              value: "{{ .Values.deployment.redis.host}}"
            - name: REDIS_PORT
              value: "{{ .Values.deployment.redis.port}}"
            - name: REDIS_TIMEOUT
              value: "{{ .Values.deployment.redis.timeout}}"
            - name: REDIS_EXPIRATION
              value: "{{ .Values.deployment.redis.expiration}}"
            - name: TO_DEVICE_SERVICE_TOPIC
              value: "{{ .Values.deployment.topic.toDeviceService}}"
            - name: PROJECT_ID
              value: "{{ .Values.deployment.projectId}}"
            - name: TENANTS_SENDING_DATA
              value: "{{ .Values.deployment.tenants.sendingData}}"
            - name: KAFKA_PRODUCER_BOOTSTRAP_SERVER
              value: "{{ .Values.deployment.kafka.producer.bootstrap.server}}"
            - name: SERVER_PORT
              value: "{{ .Values.deployment.port}}"
            - name: ACTUATOR_PORT
              value: "{{ .Values.actuator.server.port}}"
            - name: ACTUATOR_EXPOSE_ENDPOINTS
              value: "{{ .Values.actuator.endpoints.web.exposure.include}}"
            - name: JDK_JAVA_OPTIONS
              value: "{{ .Values.env.JDK_JAVA_OPTIONS }}"
