apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ss-er-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
  namespace: default
spec:
  rules:
    - host: app.singlesys.com
      http:
        paths:
          - path: /er
            pathType: Prefix
            backend:
              service:
                name: event-receiver-serv
                port:
                  number: {{.Values.deployment.port}}
  tls:
    - hosts:
        - app.singlesys.com
      secretName: tls-secret