apiVersion: v1
kind: Service
metadata:
  name: event-receiver-serv
spec:
  selector:
    app: event-receiver-app
  ports:
    - protocol: TCP
      port: {{.Values.deployment.port}}
      targetPort: {{.Values.service.target.port}}